/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cai_mr_JniVideoSummary */

#ifndef _Included_com_cai_mr_JniVideoSummary
#define _Included_com_cai_mr_JniVideoSummary
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cai_mr_JniVideoSummary
 * Method:    videoSummary
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_cai_mr_JniVideoSummary_videoSummary
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_cai_mr_JniVideoSummary
 * Method:    getFrameSize
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_cai_mr_JniVideoSummary_getFrameSize
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
